/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dani
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        beratemas = new javax.swing.JTextField();
        hargadasar = new javax.swing.JTextField();
        karat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthasil = new javax.swing.JTextArea();
        hitung = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jLabel7.setBackground(new java.awt.Color(255, 153, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFPOP1-W9", 0, 24)); // NOI18N
        jLabel1.setText("Kalkulator Gadai Emas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 20, 290, 40);

        jLabel2.setText("HARGA DASAR EMAS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 70, 120, 30);

        jLabel3.setText("BERAT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 210, 50, 20);

        jLabel4.setText("KARATASE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 140, 80, 30);
        getContentPane().add(beratemas);
        beratemas.setBounds(90, 230, 270, 40);
        getContentPane().add(hargadasar);
        hargadasar.setBounds(90, 100, 270, 40);

        karat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karatActionPerformed(evt);
            }
        });
        getContentPane().add(karat);
        karat.setBounds(90, 170, 270, 40);

        txthasil.setColumns(20);
        txthasil.setRows(5);
        jScrollPane1.setViewportView(txthasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 330, 270, 110);

        hitung.setText("HITUNG");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(190, 290, 90, 30);

        jLabel5.setText("NB : LM BATANGAN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 0, 120, 30);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 130, 0, 0);

        jLabel10.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel10.setText("jLabel8");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 100, 470, 250);

        jLabel11.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel11.setText("jLabel8");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 130, 110);

        jLabel12.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel12.setText("jLabel8");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 0, 130, 110);

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel14.setText("jLabel8");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(330, 340, 130, 110);

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel15.setText("jLabel8");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(260, 340, 130, 110);

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel16.setText("jLabel8");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(130, 340, 130, 110);

        jLabel17.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel17.setText("jLabel8");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 340, 130, 110);

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel19.setText("jLabel8");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(130, 0, 130, 110);

        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Download\\emas.png")); // NOI18N
        jLabel18.setText("jLabel8");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(260, 0, 130, 110);

        setSize(new java.awt.Dimension(475, 490));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        int harga,karatase,berat,hasil,hasil1;
        
        harga = Integer.parseInt(hargadasar.getText());
        karatase = Integer.parseInt(karat.getText());
        berat = Integer.parseInt(beratemas.getText());
        
        
        hasil = harga * karatase/24 * berat * 95/100;
       
        hasil1 = hasil * 10;
        
        
        txthasil.setText("Jumlah Pembiayaan Maksimal Rp."+hasil1);
        
        
    }//GEN-LAST:event_hitungActionPerformed

    private void karatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_karatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beratemas;
    private javax.swing.JTextField hargadasar;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField karat;
    private javax.swing.JTextArea txthasil;
    // End of variables declaration//GEN-END:variables
}
